env:
  browser: true
globals:
  angular: true
  _: true
parserOptions:
  "ecmaVersion": 6
rules:

  # Not checked:

  comma-dangle:
    - 0
    - "always-multiline"

  no-cond-assign:
    - 2
    - "except-parens"

  no-console: 1
  no-constant-condition: 2
  no-control-regex: 2
  no-debugger: 1
  no-dupe-args: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-empty: 2
  no-empty-character-class: 2
  no-ex-assign: 2
  no-extra-boolean-cast: 2
  no-extra-parens: 0
  no-extra-semi: 2
  no-func-assign: 2
  # discuss:
  no-inner-declarations:
    - 2
    - "functions"
  no-invalid-regexp: 2
  no-irregular-whitespace: 2
  no-negated-in-lhs: 2
  no-obj-calls: 2
  no-regex-spaces: 2
  no-sparse-arrays: 2
  no-unexpected-multiline: 2
  no-unreachable: 2
  use-isnan: 2
  valid-jsdoc: 1
  valid-typeof: 2

  # Best Practices
  accessor-pairs: 2
  array-callback-return: 1
  block-scoped-var: 1
  complexity:
    - 2
    - 10
  consistent-return: 1
  # discuss: multi or multi-line
  curly:
    - 1
    - "multi-line"
    - "consistent"
  default-case: 1
  # discuss
  dot-location:
    - 1
    - "property"
  dot-notation: 2
  eqeqeq:
    - 2
    - "smart"
  guard-for-in: 0
  no-alert: 2
  no-caller: 2
  no-case-declarations: 2
  no-div-regex: 2
  no-else-return: 0
  no-empty-function: 1
  no-empty-pattern: 2
  no-eq-null: 0
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-label: 2
  no-fallthrough: 1
  no-floating-decimal: 2
  no-implicit-coercion: 0
  no-implicit-globals: 2
  no-implied-eval: 2
  # discuss:
  no-invalid-this: 0
  no-iterator: 2
  no-labels: 1
  no-lone-blocks: 2
  no-loop-func: 2
  no-magic-numbers:
    - 1
    - ignore:
      - -1
      - 0
      - 1
      - 60
      - 1000
      - 24
      - 12
      - 200
      - 404
      - 500
      ignoreArrayIndexes: true
  no-multi-spaces:
    - 0
    - exceptions:
        Property: true
        VariableDeclarator: true
        ImportDeclaration: true
        AssignmentExpression: true
  no-multi-str: 1
  no-native-reassign: 2
  no-new: 0
  no-new-func: 2
  no-new-wrappers: 2
  no-octal: 2
  no-octal-escape: 2
  no-param-reassign: 0
  no-process-env: 0
  no-proto: 2
  no-redeclare: 2
  no-return-assign: 1
  no-script-url: 2
  no-self-assign: 2
  no-self-compare: 2
  no-sequences: 2
  no-throw-literal: 2
  no-unmodified-loop-condition: 2
  no-unused-expressions:
    - 1
    - allowShortCircuit: true
      allowTernary: true
  no-unused-labels: 2
  no-useless-call: 2
  no-useless-concat: 2
  no-void: 2
  no-warning-comments: 1
  no-with: 2
  radix:
    - 2
    - "as-needed"
  vars-on-top: 0
  wrap-iife: 0
  # discuss
  yoda:
    - 2
    - "never"
    - exceptRange: true

  # Variables
  init-declarations: 0
  no-catch-shadow: 0
  no-delete-var: 2
  no-label-var: 2
  no-shadow: 2
  no-shadow-restricted-names: 2
  no-undef: 2
  no-undef-init: 2
  no-undefined: 0
  no-unused-vars:
    - 1
    - vars: "all"
      args: "none"
  no-use-before-define:
    - 2
    - "nofunc"

  # node
  callback-return:
    - 2
    -
      - "callback"
      - "cb"
      - "next"
  no-mixed-requires:
    - 1
    - grouping: false
      allowCall: true
  no-new-require: 2
  no-path-concat: 2
  no-process-exit: 2

  # Style
  array-bracket-spacing:
    - 1
    - "never"
    - singleValue: false
      objectsInArrays: true
      arraysInArrays: true
  block-spacing:
    - 1
    - "always"
  brace-style:
    - 1
    - "1tbs"
    - allowSingleLine: true
  camelcase:
    - 1
    - properties: "never"
  comma-spacing:
    - 1
    - before: false
      after: true
  comma-style:
    - 1
    - "last"
  computed-property-spacing:
    - 1
    - "never"
  consistent-this:
    - 0
    - "self"
    - "vm"
  eol-last: 0
  func-names: 0
  # Discuss:
  func-style:
    - 1
    - "declaration"
  id-blacklist: 0
  id-length: 0
  id-match: 0
  indent:
    - 0
    - 2
    - SwitchCase: 1
  jsx-quotes:
    - 2
    - "prefer-double"
  key-spacing:
    - 0
    - beforeColon: false
      afterColon: true
      align: "value"
  keyword-spacing:
    - 1
    - before: true
      after: true
  linebreak-style:
    - 2
    - "unix"
  # Discuss
  lines-around-comment:
    - 1
    - beforeLineComment: false
      afterLineComment: false
      beforeBlockComment: true
      afterBlockComment: false
      allowBlockStart: true
      allowBlockEnd: true
      allowObjectStart: true
      allowObjectEnd: true
      allowArrayStart: true
      allowArrayEnd: true
  max-depth:
    - 2
    - 10
  max-len:
    - 1
    - 80
    - 4
    - ignoreUrls: true
  max-nested-callbacks:
    - 1
    - 5
  max-params:
    - 1
    - 20
  max-statements: 0
  new-cap: 0
  new-parens: 2
  newline-after-var:
    - 0
    - "always"
  newline-per-chained-call: 0
  no-array-constructor: 0
  no-bitwise: 1
  no-continue: 1
  no-inline-comments: 0
  no-lonely-if: 1
  no-mixed-spaces-and-tabs: 2
  no-multiple-empty-lines:
    - 1
    - max: 2
  no-negated-condition: 0
  no-nested-ternary: 1
  no-new-object: 1
  no-plusplus: 0
  no-restricted-syntax: 0
  no-spaced-func: 2
  no-ternary: 0
  no-trailing-spaces: 0
  no-underscore-dangle: 0
  no-unneeded-ternary: 1
  no-whitespace-before-property: 1
  object-curly-spacing:
    - 1
    - "always"
  one-var: 0
  one-var-declaration-per-line: 0
  operator-assignment: 1
  operator-linebreak: 0
  # Discuss:
  padded-blocks: 0
  quote-props:
    - 0
    - "as-needed"
  quotes:
    - 1
    - "single"
    - "avoid-escape"
  require-jsdoc: 0
  semi:
    - 2
    - "always"
  semi-spacing:
    - 1
    - before: false
      after: true
  sort-imports: 1
  sort-vars: 0
  space-before-blocks:
    - 1
    - "always"
  space-before-function-paren:
    - 1
    - "always"
  space-in-parens:
    - 1
    - "never"
  space-infix-ops: 2
  space-unary-ops:
    - 1
    - words: true
      nonwords: false
  spaced-comment:
    - 2
    - "always"
  wrap-regex: 0
